/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wzf_ndkstudy_jni_HelloJNI */

#ifndef _Included_com_wzf_ndkstudy_jni_HelloJNI
#define _Included_com_wzf_ndkstudy_jni_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wzf_ndkstudy_jni_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wzf_ndkstudy_jni_HelloJNI_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_wzf_ndkstudy_jni_HelloJNI
 * Method:    sayHelloString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wzf_ndkstudy_jni_HelloJNI_sayHelloString
  (JNIEnv *, jobject);

/*
 * Class:     com_wzf_ndkstudy_jni_HelloJNI
 * Method:    getStringFromC2
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wzf_ndkstudy_jni_HelloJNI_getStringFromC2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_wzf_ndkstudy_jni_HelloJNI
 * Method:    changeKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wzf_ndkstudy_jni_HelloJNI_changeKey
  (JNIEnv *, jobject);

/*
 * Class:     com_wzf_ndkstudy_jni_HelloJNI
 * Method:    runJavaMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wzf_ndkstudy_jni_HelloJNI_runJavaMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_wzf_ndkstudy_jni_HelloJNI
 * Method:    callConstructor
 * Signature: ()Ljava/util/Date;
 */
JNIEXPORT jobject JNICALL Java_com_wzf_ndkstudy_jni_HelloJNI_callConstructor
  (JNIEnv *, jobject);

/*
 * Class:     com_wzf_ndkstudy_jni_HelloJNI
 * Method:    callParentMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wzf_ndkstudy_jni_HelloJNI_callParentMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_wzf_ndkstudy_jni_HelloJNI
 * Method:    chineseChars
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wzf_ndkstudy_jni_HelloJNI_chineseChars
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_wzf_ndkstudy_jni_HelloJNI
 * Method:    giveSortArray
 * Signature: ([I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_wzf_ndkstudy_jni_HelloJNI_giveSortArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_wzf_ndkstudy_jni_HelloJNI
 * Method:    localRef
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wzf_ndkstudy_jni_HelloJNI_localRef
  (JNIEnv *, jobject);

/*
 * Class:     com_wzf_ndkstudy_jni_HelloJNI
 * Method:    createGlobalRef
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wzf_ndkstudy_jni_HelloJNI_createGlobalRef
  (JNIEnv *, jobject);

/*
 * Class:     com_wzf_ndkstudy_jni_HelloJNI
 * Method:    getGlobalRef
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wzf_ndkstudy_jni_HelloJNI_getGlobalRef
  (JNIEnv *, jobject);

/*
 * Class:     com_wzf_ndkstudy_jni_HelloJNI
 * Method:    deleteGlobalRef
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wzf_ndkstudy_jni_HelloJNI_deleteGlobalRef
  (JNIEnv *, jobject);

/*
 * Class:     com_wzf_ndkstudy_jni_HelloJNI
 * Method:    exception
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wzf_ndkstudy_jni_HelloJNI_exception
  (JNIEnv *, jobject);

/*
 * Class:     com_wzf_ndkstudy_jni_HelloJNI
 * Method:    jniCache
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wzf_ndkstudy_jni_HelloJNI_jniCache
  (JNIEnv *, jobject);

/*
 * Class:     com_wzf_ndkstudy_jni_HelloJNI
 * Method:    initIds
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wzf_ndkstudy_jni_HelloJNI_initIds
  (JNIEnv *, jclass);


/*
 * Class:     com_wzf_ndkstudy_jni_HelloJNI
 * Method:    threadTest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wzf_ndkstudy_jni_HelloJNI_threadTest
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
